#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| ULTRA NUCLEAR FIX: Override ALL problematic helper functions BEFORE autoload
|--------------------------------------------------------------------------
*/

define('SAFE_PLACEHOLDER', '/vendor/igniter-orange/images/favicon.ico');

if (!function_exists('media_thumb')) {
    function media_thumb(?string $path, array $options = []): string
    {
        return SAFE_PLACEHOLDER;
    }
}

if (!function_exists('resize')) {
    function resize($url = null, $width = 0, $height = 0, $options = [])
    {
        return $url ?: SAFE_PLACEHOLDER;
    }
}

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);
