[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"
watchPatterns = ["**/*"]

[deploy]
numReplicas = 1
healthcheckPath = "/health.json"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
